spring:
  application:
    name: api

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coupon_example
    username: root
    password: 1234

  data:
    redis:
      host: 127.0.0.1
      port: 6379
